/* ------------------------------------------------------------------
   items.js

   CALIBRATION ENTRIES. Three real, voice-locked entries, one per
   content type, used to tune the writing voice before the rest are
   written. Stat ranges still get a fact-verification pass before
   these go live.

   Types covered:
     jmod        magic base   | no history | hidden value
     verdungos   unique       | no history | roll-dependent
     stone-of-jordan  unique  | has history | historic significance

   Order in this array is the rotation order. Hand-order it so the site
   does not open on five S tiers in a row. `obscurity` is editorial only
   and never rendered.

   LOCALIZATION
   Any prose field (name, alias, type, why, history, ifYouFind, and each
   tooltip line) can be either:
     "a plain string"                 English only, the normal case
     { en: "...", de: "..." }         per-language, English is the fallback
   A missing language falls back to English, so partial translations are
   safe. Universal fields stay plain: slug, quality, sprite, valueTier,
   rarityTier, obscurity. Optional `title` overrides the on-page H1 shown
   under the header; use it when the in-game tooltip name would mislead
   (the Occy Ring displays in game as a Stone of Jordan). It defaults to
   `name`. The `alias` renders as a small subtitle beneath the title.
   Socketed items: `sockets` (a count) draws that many empty socket holes over
   the sprite by default. Optional `grid` is the item's inventory size in cells,
   [columns, rows]. The socket holes are laid out in that many columns and fill
   row by row, matching the game: a single-column base (an orb, a wand) stacks
   its sockets vertically, a two-wide base fills two per row. A leftover socket
   on its own row is centered, not pushed to one side. Only the column count
   changes the layout; the row value is recorded for reference. Omit `grid`
   and the layout falls back to two columns. Optional `fill` is an array of socketable sprite
   paths (img/socketables/*); when present, a button fills the holes with them,
   and any `fillTip` lines (the stats those socketables add) appear in the
   tooltip. `fillLabel` sets the button text. If `fill` is set its length is
   the socket count, so `sockets` is only needed when an item has sockets but
   no defined fill. Set `filled: true` for a COMPLETE item that came with its
   runes/gems already in (e.g. a rare with Lo Lo socketed): the socketables show
   by default and there is no fill button. The socketables' stats are part of the
   base tooltip in that case, so do NOT also add `fillTip` (it would double up).
   Optional `era` (e.g. "Classic") renders a tag beside the tiers marking
   the game the item mattered in; leave it off for current Expansion items
   so the tag stays meaningful. Optional `lastPatch` (e.g. "1.09") marks an item
   whose shown version no longer drops; it renders as a "Last seen" tag
   beside the tiers. Use it for legacy / pre-nerf entries.
   Optional `illicit` marks contraband that cannot legitimately exist. Set it to
   "Hacked" (an external item-editing hack, renders a red tag) or "Bugged" (an
   in-game glitch like the ethereal-socket defense bug, renders an amber tag).
   The why/history carry the story; the tag flags that it is not a real drop.
   To turn a language on, add it to AVAILABLE_LANGS
   and its UI block in app.js. The switcher appears automatically.
   Translations are native rewrites only, never machine translation.

   TOOLTIP COLORS (match the game, verified against real screenshots)
   The tooltip replicates the in-game item display. Rules:
     - name + type    take the item quality color automatically (from `quality`):
                      unique gold, set green, rare yellow, magic blue, rune orange,
                      normal white. Do not color these by hand.
     - base stats     Defense, Damage, Durability, Required Strength/Level:
                      white  -> { t: "Defense: 148", c: "white" }
                      Render requirements as WHITE (assume met) for a clean showcase.
     - class restrict "(Druid Only)" and similar standalone restriction lines:
                      red    -> { t: "(Druid Only)", c: "red" }
     - magic props    +skills, +%ED, resists, sockets, "Can be inserted...": the
                      DEFAULT. Plain string -> renders blue. e.g. "+120% Enhanced Defense"
     - grey/gold      also available via c: "grey" / c: "gold" if ever needed.
   So a typical unique tooltip array is: white base-stat lines, then an optional red
   restriction, then plain-string blue property lines. `type` holds the base ("Mithril
   Coil", "Ring"); leave it "" for runes, and "" for magic items whose base is already
   inside the name.
------------------------------------------------------------------ */

const ITEMS = [
  {
    slug: "jmod",
    grid: [2, 3],
    name: "Jeweler's Monarch of Deflecting",
    alias: "JMOD",
    quality: "magic",
    type: "",
    sprite: "img/monarch.png",
    fill: ["img/rainbow-facet.png", "img/rainbow-facet.png", "img/rainbow-facet.png", "img/rainbow-facet.png"],
    fillLabel: "socket 4 lightning facets",
    fillTip: ["-20% to Enemy Lightning Resistance", "+20% to Lightning Skill Damage"],
    tooltip: [
      { t: "Defense: 134", c: "white" },
      { t: "Chance to Block: 67%", c: "white" },
      { t: "Durability: 77 of 86", c: "white" },
      { t: "Required Strength: 156", c: "white" },
      { t: "Required Level: 54", c: "white" },
      "+30% Faster Block Rate",
      "20% Increased Chance of Blocking",
      "Socketed (4)"
    ],
    valueTier: "S",
    rarityTier: "Very Rare",
    obscurity: 3,
    why: "A blue shield that trades for a dozen high runes. It is not a runeword base, it is better than one. Four sockets, thirty faster block, twenty increased block, all on a light shield anyone can carry. You fill the sockets yourself, usually with Rainbow Facets, and get a max-block shield tuned to your build that no plain runeword can match. Lightning javazons in particular hunt these. It looks like vendor trash and gambles for a fortune.",
    history: null,
    ifYouFind: "Four sockets on a magic Monarch with the block rolls. That is it. You socket it yourself, so the empty shell is the prize."
  },
  {
    slug: "tyraels-might",
    name: "Tyrael's Might",
    alias: "TM",
    quality: "unique",
    type: "Sacred Armor",
    sprite: "img/tyraels-might.png",
    tooltip: [
      { t: "Defense: 1502", c: "white" },
      { t: "Required Level: 84", c: "white" },
      "+150% Enhanced Defense",
      "+100% Damage to Demons",
      "+20% Faster Run/Walk",
      "+30 to Strength",
      "All Resistances +30",
      "Cannot Be Frozen",
      "Requirements -100%",
      "Slain Monsters Rest in Peace",
      "Indestructible"
    ],
    valueTier: "B",
    rarityTier: "Mythic",
    obscurity: 2,
    why: "The rarest item in the game. Not one of the rarest. By the drop numbers, the single hardest thing to see. It is a good armor too, with no strength requirement and a wall of resistances, but it is not Enigma and never was. People want it because almost nobody has one.",
    history: "For years Tyrael's Might was the item you heard about and never saw. Its drop rate is the lowest in the game, low enough that plenty of thousand-hour players have never held one. The stats are good. They are not the best in the slot. The price is the rarity, and nothing else.",
    ifYouFind: "Almost nobody does. If you somehow do, it is a trophy first and gear second."
  },
  {
    slug: "stone-of-jordan",
    name: "Stone of Jordan",
    alias: "SOJ",
    quality: "unique",
    type: "Ring",
    sprite: "img/uniques/stone-of-jordan.webp",
    tooltip: [
      { t: "Required Level: 29", c: "white" },
      "+1 to All Skills",
      "Adds 1-12 Lightning Damage",
      "+20 to Mana",
      "Increase Maximum Mana 25%"
    ],
    valueTier: "D",
    rarityTier: "Common",
    obscurity: 2,
    why: "A ring with plus one to all skills and some mana. Common, and cheap on a mature ladder. New characters still run one for the early skill boost.",
    history: "The Stone of Jordan was the currency of Diablo 2 for years. Not a figure of speech. People priced gear in SOJs the way you would price it in dollars. Then duping flooded the realm with them and the currency collapsed, dragging every other price up with it. Blizzard's fix is still in the game. A hidden counter tracks Stones of Jordan sold to town vendors, and when enough get sold, Diablo Clone spawns and comes looking. One ring created a permanent boss and the sink that eats the ring. Nothing else in the game has a story like it.",
    ifYouFind: null
  },
  {
    slug: "wraith-crack",
    name: "Wraith Crack",
    alias: "the six-figure rare",
    quality: "rare",
    type: "Legendary Mallet",
    sprite: "img/legendary-mallet.png",
    grid: [2, 3],
    fill: ["img/socketables/rune-lo.png", "img/socketables/rune-lo.png"],
    filled: true,
    tooltip: [
      { t: "One-Hand Damage: 293 to 404", c: "white" },
      { t: "Durability: 65 of 65", c: "white" },
      { t: "Required Strength: 179", c: "white" },
      { t: "Required Level: 73", c: "white" },
      { t: "Mace Class - Very Fast Attack Speed", c: "white" },
      "+40% Increased Attack Speed",
      "+291% Enhanced Damage",
      "+49 to Maximum Damage (Based on Character Level)",
      "+1633 to Attack Rating (Based on Character Level)",
      "+1 Cold Damage",
      "+40% Deadly Strike",
      "Repairs 1 Durability in 20 Seconds",
      "+50% Damage to Undead",
      "Ethereal (Cannot be Repaired)",
      "Socketed (2)"
    ],
    valueTier: "S",
    rarityTier: "Mythic",
    obscurity: 4,
    why: "Every line here is legitimate, and that is the point. A rare that rolled near the ceiling on everything at once: two hundred ninety one enhanced damage just under the cap, forty attack speed, forty deadly strike from the two Lo runes, all on an ethereal fast mace. Nothing unique or runeword beats it for a straight melee build. The odds of the game rolling one item this well are almost none, which is why it became the most famous rare in the game.",
    history: "Wraith Crack is the rare people tell stories about. The legend has it selling for a six-figure sum, somewhere near a hundred and twenty thousand dollars, though no record of the sale survives and the figure has the ring of folklore. What is real is why the story stuck. A perfect legitimate roll on the best melee base, one of one, is exactly the kind of item a community turns into a myth.",
    ifYouFind: "There is no second one to roll. Every affix landed near its ceiling on the same legitimate item, which is a coincidence the game has essentially never repeated."
  },
  {
    slug: "deaths-web",
    name: "Death's Web",
    alias: "Web",
    quality: "unique",
    type: "Unearthed Wand",
    sprite: "img/uniques/deaths-web.webp",
    tooltip: [
      { t: "One-Hand Damage: 22 to 28", c: "white" },
      { t: "Required Level: 66", c: "white" },
      { t: "Required Strength: 25", c: "white" },
      "+2 to All Skills",
      "+2 to Poison and Bone Spells (Necromancer Only)",
      "-50% to Enemy Poison Resistance",
      "+12 Life after each Kill",
      "+12 Mana after each Kill",
      "+50% Damage to Undead"
    ],
    valueTier: "S",
    rarityTier: "Very Rare",
    obscurity: 3,
    why: "The poison necromancer's endgame wand, and the reason the build works at the top level. Minus enemy poison resistance is the whole point, and this rolls to minus fifty. Add two skills and two to poison and bone on top. There is no substitute. If you play poison necro seriously, you own one or you are working toward it.",
    history: null,
    ifYouFind: "The poison resistance roll is the item. Minus fifty is perfect. Anything in the forties still sells."
  },
  {
    slug: "armageddon-fletch",
    name: "Armageddon Fletch",
    alias: "2/20 caster amulet",
    quality: "rare",
    type: "Amulet",
    sprite: "img/rare-amulet.png",
    tooltip: [
      { t: "Required Level: 41", c: "white" },
      "+2 to Sorceress Skill Levels",
      "+20% Faster Cast Rate",
      "+18 to Strength",
      "+55 to Life",
      "+69 to Mana",
      "All Resistances +23"
    ],
    valueTier: "A",
    rarityTier: "Very Rare",
    obscurity: 4,
    why: "A rare amulet that quietly beats the famous unique ones. Two sorceress skills and twenty faster cast rate, then life, strength and all resistances piled on top. Mara's gets the attention. An amulet like this does more for a caster, and it comes with no gold name to tip you off. The random title is doing a lot of work to hide how good it is.",
    history: null,
    ifYouFind: "Two class skills and twenty cast rate on one amulet is the jackpot. Everything after that is a bonus most uniques cannot match."
  },
  {
    slug: "shadow-claw",
    grid: [1, 3],
    sockets: 2,
    name: "Shadow Claw",
    alias: "godly rare trapsin claw",
    quality: "rare",
    type: "Greater Talons",
    sprite: "img/greater-talons.png",
    tooltip: [
      { t: "One-Hand Damage: 21 to 36", c: "white" },
      { t: "Durability: 60 of 69", c: "white" },
      { t: "(Assassin Only)", c: "red" },
      { t: "Required Dexterity: 79", c: "white" },
      { t: "Required Strength: 79", c: "white" },
      { t: "Required Level: 52", c: "white" },
      { t: "Claw Class - Very Fast Attack Speed", c: "white" },
      "+2 to Assassin Skills",
      "+40% Increased Attack Speed",
      "+14% Faster Hit Recovery",
      "+3 to Mind Blast (Assassin Only)",
      "+3 to Lightning Sentry (Assassin Only)",
      "+3 to Weapon Block (Assassin Only)",
      "+15 to Strength",
      "Replenish Life +13",
      "+30 to Mana",
      "Lightning Resist +40%",
      "Socketed (2)"
    ],
    valueTier: "A",
    rarityTier: "Very Rare",
    obscurity: 4,
    why: "A rare claw that out-stacks anything a trapsin can build. Two to all assassin skills, then three more each to Lightning Sentry, Mind Blast and Weapon Block, plus forty attack speed, maxed lightning resist, and two open sockets. No unique claw and no runeword gives that combination. The game has to land every one of those lines at once, which almost never happens. It reads as a yellow drop and outclasses the gold ones beside it.",
    history: null,
    ifYouFind: "Count the skills. Two to all, plus three each to three separate assassin skills on one claw, is the jackpot. Add the two sockets and the resistance and it is a top trapsin weapon."
  },
  {
    slug: "white-ring",
    name: "Ring",
    title: "White Ring",
    alias: "hacked absorb ring",
    quality: "normal",
    type: "",
    sprite: "img/ring.png",
    illicit: "Hacked",
    tooltip: [
      "100% Faster Run/Walk",
      "100% Increased Attack Speed",
      "Adds 63-127 Damage",
      "20% Life Stolen per Hit",
      "Fire Absorb 96%",
      "Lightning Absorb 96%",
      "Cold Absorb 96%"
    ],
    valueTier: "S",
    rarityTier: "Mythic",
    obscurity: 5,
    why: "A plain white ring with no name and no requirements, carrying the best absorb in the game three times over. Ninety six percent taken off fire, lightning and cold at once, with a hundred faster run and a hundred attack speed alongside. No legitimate ring rolls any of this. On the old realms a White Ring made a dueler nearly immune to elements, which is exactly why it was contraband gold.",
    history: "The White Ring came off open Battle.net, where the client could build items with impossible stats. Import and dupe bugs carried it onto the closed realms where real trading happened, and for years it was one of the most coveted duel items nobody could legally own. Later patches purged it. It has no place in the loot table and never did.",
    ifYouFind: "You cannot, not honestly. A no-requirement ring with triple absorb is a hacked item. Using one now gets an account banned, not rich."
  },
  {
    slug: "ith",
    grid: [2, 4],
    sockets: 6,
    name: "Ith",
    alias: "the item hack's signature",
    quality: "normal",
    type: "Colossus Blade",
    sprite: "img/colossus-blade.png",
    illicit: "Hacked",
    tooltip: [
      { t: "One-Hand Damage: 220 to 668", c: "white" },
      { t: "Two-Hand Damage: 610 to 1001", c: "white" },
      { t: "Required Strength: 179", c: "white" },
      { t: "Required Level: 63", c: "white" },
      { t: "Sword Class - Very Fast Attack Speed", c: "white" },
      "Indestructible",
      "+2 to All Skill Levels",
      "60% Increased Attack Speed",
      "200% Faster Hit Recovery",
      "+400% Enhanced Damage",
      "4% Mana Stolen per Hit",
      "Hit Blinds Target +33",
      "All Resistances +76",
      "Ethereal (Cannot be Repaired)",
      "Socketed (6)"
    ],
    valueTier: "S",
    rarityTier: "Mythic",
    obscurity: 5,
    why: "Count how many of these lines are impossible. Two to all skills, two hundred percent faster hit recovery, seventy six all resistance, four hundred enhanced damage, six sockets, ethereal and indestructible, on one weapon named after a rune. No legitimate item carries half of it. Ith is the fingerprint of the old item hack, the same stat block stamped onto swords, bows and more.",
    history: "In the early years, open Battle.net let the client edit items freely, and import bugs ferried those edited items onto the closed realms where they traded as real. A whole wave of them shared one giveaway name, Ith, and one impossible stat block. They were the loudest proof that part of the closed-realm economy was never legitimate. Purges removed them, and they cannot exist in the modern game.",
    ifYouFind: "You will only see one in an old screenshot. Ith is a hacked item, not a drop, and it is the same template on every base it was stamped onto."
  },
  {
    slug: "hex-charm",
    name: "Hexing Small Charm of Immolating Arrow",
    title: "Hex Charm",
    alias: "hacked +90 stat charm",
    quality: "magic",
    type: "",
    sprite: "img/small-charm.png",
    illicit: "Hacked",
    tooltip: [
      { t: "Keep in Inventory to Gain Bonus", c: "grey" },
      { t: "Required Level: 42", c: "white" },
      "+90 to Strength",
      "+90 to Dexterity",
      "+90 to Vitality"
    ],
    valueTier: "A",
    rarityTier: "Mythic",
    obscurity: 5,
    why: "A small charm gives one small bonus. This one gives ninety strength, ninety dexterity and ninety vitality out of a single inventory square. The name is a real magic charm's, with numbers no charm can roll bolted underneath. A row of these turned any character into something the game was never built to allow.",
    history: "Hex charms came from the same item-editing era as the White Ring and the Ith weapons. On open Battle.net the client could write any value into an item, and bugs ferried them onto the closed realms. A charm was the perfect smuggler: tiny, stackable, and easy to hide in an inventory full of legitimate ones. They were purged, and no charm rolls like this.",
    ifYouFind: "Ninety to a stat on a small charm is a hacked value, full stop. It is contraband, not a lucky roll."
  },
  {
    slug: "carrion-song",
    name: "Carrion Song",
    alias: "classic rare bow",
    quality: "rare",
    type: "Gothic Bow",
    era: "Classic",
    sprite: "img/rare-bow.png",
    tooltip: [
      { t: "Two-Hand Damage: 30 to 163", c: "white" },
      { t: "Required Dexterity: 95", c: "white" },
      { t: "Required Strength: 76", c: "white" },
      { t: "Required Level: 26", c: "white" },
      { t: "Bow Class - Very Fast Attack Speed", c: "white" },
      "Requirements -20%",
      "+1 to Amazon Skill Levels",
      "+132 to Attack Rating",
      "+18 to Maximum Damage",
      "Increased Attack Speed"
    ],
    valueTier: "C",
    rarityTier: "Very Rare",
    obscurity: 4,
    why: "A yellow bow with a random name, and in classic Diablo 2 that was the dream. Before runewords, before Windforce, a rolled rare like this was the bowazon endgame. A class skill on a bow you can hold at level 26, very fast attack speed, a stack of attack rating and max damage. The name means nothing. The game bolts two words together at random. The rolls are everything, and rolls like these almost never landed.",
    history: null,
    ifYouFind: "This is what people mean when they say do not vendor yellows. Read every line first."
  },
  {
    slug: "phoenix-hybrid",
    name: "Phoenix",
    alias: "hacked hybrid runeword",
    quality: "runeword",
    type: "Monarch",
    sprite: "img/monarch.png",
    illicit: "Hacked",
    tooltip: [
      { t: "Defense: 171", c: "white" },
      { t: "Chance to Block: 52%", c: "white" },
      { t: "Smite Damage: 12 to 34", c: "white" },
      { t: "Durability: 98 of 98", c: "white" },
      { t: "Required Strength: 156", c: "white" },
      { t: "Required Level: 65", c: "white" },
      "+2 to All Skills",
      "35% Faster Cast Rate",
      "65% Faster Hit Recovery",
      "16% Enhanced Defense",
      "+260 Defense vs. Missile",
      "+22 to Vitality",
      "+50 to Life",
      "+112 to Mana",
      "+5% to Maximum Lightning Resist",
      "+10% to Maximum Fire Resist",
      "+8 Magic Absorb",
      "Increase Maximum Durability 15%"
    ],
    valueTier: "A",
    rarityTier: "Mythic",
    obscurity: 5,
    why: "It borrows a real runeword's name and none of its stats. Phoenix is Vex Vex Lo Jah, and a real one carries a Redemption aura, minus enemy fire resistance and a wall of fire damage. This one has two to all skills, thirty five faster cast and sixty five faster hit recovery instead, a blend no runeword produces. It is a hacked item hiding behind a legitimate name, built to pass as the real thing.",
    history: "Hybrid runewords were among the sneakiest hacks. Take a valid runeword name, swap the stat block for a better mix, and it slips through trades that check the runes but not the numbers. They came from the same open-realm editing that made the White Ring and Ith. The tell is the stats: hold them against the real recipe and they never line up.",
    ifYouFind: "Look up the runeword. If the runes read Phoenix but the stats are not Phoenix, it is a hybrid hack. The name is real, the item is not."
  },
  {
    slug: "imp-shank",
    name: "Imp Shank",
    alias: "tri-res rare boots",
    quality: "rare",
    type: "Mesh Boots",
    sprite: "img/rare-boots.png",
    tooltip: [
      { t: "Defense: 39", c: "white" },
      { t: "Durability: 16 of 16", c: "white" },
      { t: "Required Strength: 65", c: "white" },
      { t: "Required Level: 26", c: "white" },
      "+30% Faster Run/Walk",
      "Cold Resist +12%",
      "Lightning Resist +36%",
      "Fire Resist +46%",
      "Half Freeze Duration",
      "34% Better Chance of Getting Magic Items"
    ],
    valueTier: "B",
    rarityTier: "Very Rare",
    obscurity: 4,
    why: "Boots are a slot most people fill with a unique and forget. This rare beats most of them. Thirty faster run and walk, three resistances at once, half freeze duration, and a slice of magic find. A single rare covering that many needs almost never happens. The game has to roll every one of those lines together, and it rarely does.",
    history: null,
    ifYouFind: "Tri-res on boots is the hard part. Everything else here is a bonus."
  },
  {
    slug: "iceblink",
    name: "Iceblink",
    alias: "the freeze-lock armor",
    quality: "unique",
    type: "Splint Mail",
    sprite: "img/uniques/iceblink.webp",
    tooltip: [
      { t: "Defense: 172", c: "white" },
      { t: "Durability: 30 of 30", c: "white" },
      { t: "Required Strength: 51", c: "white" },
      { t: "Required Level: 22", c: "white" },
      "Freezes target",
      "+80% Enhanced Defense",
      "Cold Resist +30%",
      "Magic Damage Reduced by 1",
      "+4 to Light Radius"
    ],
    valueTier: "D",
    rarityTier: "Uncommon",
    obscurity: 4,
    why: "A level twenty-two unique nobody stops for, and one of the only body armors in the game that freezes what you hit. A frozen enemy cannot attack, so a melee twink or an Act 2 merc wearing this walks through Normal untouched. Anything killed while frozen shatters and leaves no corpse, which quietly denies the other side every corpse it wanted. It costs a chipped gem and does something almost nothing else can.",
    history: null,
    ifYouFind: "The roll does not matter here. Keep it for a leveling character or a merc, and cube it up to a bigger base later if you want the defense."
  },
  {
    slug: "grim-fist",
    name: "Grim Fist",
    alias: "+2 skill javazon gloves",
    quality: "rare",
    type: "Light Gauntlets",
    sprite: "img/light-gauntlets.png",
    tooltip: [
      { t: "Defense: 13", c: "white" },
      { t: "Durability: 16 of 18", c: "white" },
      { t: "Required Strength: 45", c: "white" },
      { t: "Required Level: 36", c: "white" },
      "+2 to Javelin and Spear Skills (Amazon Only)",
      "+20% Increased Attack Speed",
      "3% Mana Stolen per Hit",
      "3% Life Stolen per Hit",
      "+13% Enhanced Defense"
    ],
    valueTier: "A",
    rarityTier: "Very Rare",
    obscurity: 4,
    why: "Gloves are an afterthought slot, which is exactly why this pair hides. Two to the whole javelin and spear tree, then twenty attack speed and a maxed three and three life and mana leech on top. A javazon gets a skill level here that no unique glove can offer, the leech to stay alive, and the speed to throw faster. It reads as a junk yellow. It is a build-defining glove for the right amazon.",
    history: null,
    ifYouFind: "The plus two skills is the prize, and it only comes on gloves as a rare roll. Three life and three mana leech, both maxed, on the same pair is what turns a good glove into a keeper."
  },
  {
    slug: "glitched-arreats",
    grid: [2, 2],
    sockets: 1,
    name: "Arreat's Face",
    title: "Glitched Arreat's Face",
    alias: "the Zod-bug antique",
    quality: "unique",
    type: "Slayer Guard",
    sprite: "img/arreats-face.png",
    illicit: "Bugged",
    tooltip: [
      { t: "Defense: 641", c: "white" },
      { t: "(Barbarian Only)", c: "red" },
      { t: "Required Strength: 108", c: "white" },
      { t: "Required Level: 42", c: "white" },
      "Indestructible",
      "+2 to Combat Skills (Barbarian Only)",
      "+2 to Barbarian Skill Levels",
      "+30% Faster Hit Recovery",
      "+30% Enhanced Damage",
      "20% Bonus to Attack Rating",
      "+60 to Attack Rating",
      "6% Life Stolen per Hit",
      "+199% Enhanced Defense",
      "+29 to Strength",
      "+29 to Dexterity",
      "All Resistances +30",
      "Ethereal (Cannot be Repaired)",
      "Socketed (1)"
    ],
    valueTier: "A",
    rarityTier: "Mythic",
    obscurity: 5,
    why: "A normal Arreat's Face cannot be indestructible, and cannot show six hundred defense. This one is both. It is an ethereal Arreat's that a Zod rune locked permanently indestructible, keeping the ethereal defense bonus with no durability left to lose, and the defense was doubled again by the old ethereal socketing bug. The current game cannot produce it: eternal, ethereal, and armored past its own ceiling.",
    history: "In patch 1.09, socketing a Zod rune into an ethereal item without bonus durability locked it indestructible while keeping the ethereal bonus, an interaction later patches changed. Pair it with the ethereal socketing bug that doubled defense, and you get pieces like this, eternal and stronger than the item was ever meant to be. Collectors call them antiques. They were made in a version of the game that no longer exists and cannot be remade.",
    ifYouFind: "An indestructible ethereal unique with defense above its own cap is a relic of the old patches. A collector's antique, not something you drop or build today."
  },
  {
    slug: "windforce-08",
    name: "Windforce",
    alias: "1.08 Windforce",
    quality: "unique",
    type: "Hydra Bow",
    sprite: "img/hydra-bow.png",
    lastPatch: "1.08",
    tooltip: [
      { t: "Two-Hand Damage: 35 to 547", c: "white" },
      { t: "Required Level: 73", c: "white" },
      { t: "Required Strength: 134", c: "white" },
      { t: "Required Dexterity: 167", c: "white" },
      "+250% Enhanced Damage",
      "+309 to Maximum Damage (Based on Character Level)",
      "20% Increased Attack Speed",
      "7% Mana Stolen per Hit",
      "Heal Stamina Plus 30%",
      "+35 to Dexterity",
      "Knockback"
    ],
    valueTier: "B",
    rarityTier: "Mythic",
    obscurity: 4,
    why: "Windforce is the bow every bowazon wanted, the two-hander with the highest maximum damage in the game and a knockback that kept everything off you. This is the version that stopped dropping in 2001. Today's Windforce rolls five dexterity. This one rolls thirty five. Thirty extra dexterity is free attack rating and block that no modern copy can reach, on the best bow base there is.",
    history: "For years the Windforce was the endgame bowazon weapon, the drop that made the build. In its first year it carried plus thirty five dexterity. Patch 1.09 cut that to plus five and handed it strength instead. Because an item's stats freeze the moment it is created, every Windforce made before the patch kept its thirty five, and none made since can match it. Collectors trade these as their own tier and call them 08 Windforces.",
    ifYouFind: "The dexterity line is the whole tell. Thirty five means it was born before patch 1.09; five means it dropped any time in the two decades since."
  },
  {
    slug: "arkaines-valor",
    name: "Arkaine's Valor",
    alias: "legacy Arkaine's",
    quality: "unique",
    type: "Balrog Skin",
    sprite: "img/arkaines-valor.png",
    tooltip: [
      { t: "Defense: 1664", c: "white" },
      { t: "Required Strength: 165", c: "white" },
      { t: "Required Level: 85", c: "white" },
      "Indestructible",
      "+2 to All Skill Levels",
      "30% Faster Hit Recovery",
      "+200% Enhanced Defense",
      "+247 to Vitality (Based on Character Level)",
      "+198 to Life (Based on Character Level)",
      "Fire Resist +50%"
    ],
    valueTier: "B",
    rarityTier: "Mythic",
    lastPatch: "1.09",
    obscurity: 4,
    why: "This is not the Arkaine's Valor that drops today. This is the old one. Before the nerf it gave two and a half vitality and two life for every character level, plus two to all skills, indestructible, and fire resist, all on one body armor. At level ninety-nine that is hundreds of free vitality and life. The current version was cut down hard, so a copy like this can no longer drop.",
    history: "Arkaine's Valor was so strong before the 1.10 patch that it became one of the most duped armors in the game. Blizzard gutted the life and vitality bonus and left the weaker version dropping in its place. The old copies were never deleted, only frozen out of the loot table. The ones still around are relics from a version of Diablo 2 that no longer exists, and they thin out every year as old accounts expire.",
    ifYouFind: "It does not drop anymore. Anyone offering one is trading a survivor from an old patch, not a fresh find."
  },
  {
    slug: "legacy-hellfire-torch",
    name: "Hellfire Torch",
    alias: "legacy Torch (25% Firestorm)",
    quality: "unique",
    type: "Large Charm",
    sprite: "img/uniques/legacy-hellfire-torch.webp",
    tooltip: [
      { t: "Required Level: 75", c: "white" },
      "25% Chance to Cast Level 10 Firestorm on Striking",
      "+3 to Sorceress Skills",
      "+20 to All Attributes",
      "All Resistances +20",
      "+8 to Light Radius",
      "Level 30 Hydra (10 Charges)"
    ],
    valueTier: "A",
    rarityTier: "Mythic",
    lastPatch: "1.12",
    obscurity: 4,
    why: "Everyone knows the Hellfire Torch. Almost nobody has seen this one. The current Torch casts Firestorm five percent of the time. The old one cast it twenty-five. Five times the fire, on a charm that was already an endgame staple. It stopped dropping in this form, so every 25 percent Torch is a survivor from before the nerf.",
    history: "The Torch came from the Pandemonium Event added in patch 1.11, and for its first years it cast Firestorm on a quarter of your hits. That was a wall of free fire on a charm people fought the Ubers to earn. Patch 1.13 cut it to five percent. The old copies kept their twenty-five, so the legacy Torch became a collector's version of an item almost everyone already owns.",
    ifYouFind: "Check the Firestorm line. Twenty-five percent means it is pre-1.13, and worth far more than the Torch in your stash."
  },
  {
    slug: "siggards-stealth",
    name: "Siggard's Stealth",
    alias: "the renamed Nosferatu's Coil",
    quality: "unique",
    type: "Vampirefang Belt",
    sprite: "img/siggards-stealth.png",
    tooltip: [
      { t: "Defense: 63", c: "white" },
      { t: "Required Level: 51", c: "white" },
      { t: "Required Strength: 50", c: "white" },
      "+10% Increased Attack Speed",
      "7% Life Stolen per Hit",
      "Slows Target by 10%",
      "+2 to Mana after each Kill",
      "+15 to Strength",
      "-3 to Light Radius"
    ],
    valueTier: "C",
    rarityTier: "Very Rare",
    lastPatch: "1.09",
    obscurity: 5,
    why: "Look at the name. That belt does not exist anymore. The stats are an ordinary Nosferatu's Coil, attack speed and life steal, nothing a current player would chase. What makes it a collector piece is the name itself. Nothing has dropped with it in over twenty years.",
    history: "In the 1.10 patch Blizzard reshuffled the unique item files. The belt that had been Nosferatu's Coil was renamed Siggard's Stealth, and a new Nosferatu's Coil started dropping in its place with the same stats. Every existing copy changed its name on the spot. So a Siggard's Stealth is proof of age. It is a Nosferatu's Coil from before the patch, wearing a name the game no longer hands out.",
    ifYouFind: "You cannot find one, only inherit one. The name is the whole story. The stats are beside the point."
  },
  {
    slug: "crown-of-ages",
    name: "Crown of Ages",
    alias: "perfect CoA",
    quality: "unique",
    type: "Corona",
    sprite: "img/uniques/crown-of-ages.webp",
    tooltip: [
      { t: "Defense: 399", c: "white" },
      { t: "Required Level: 82", c: "white" },
      { t: "Required Strength: 174", c: "white" },
      "+1 to All Skills",
      "+50% Enhanced Defense",
      "Physical Damage Received Reduced by 15%",
      "All Resistances +30",
      "+30% Faster Hit Recovery",
      "Socketed (2)",
      "Indestructible"
    ],
    valueTier: "A",
    rarityTier: "Very Rare",
    obscurity: 2,
    why: "Everyone knows the helm. Almost nobody prices the roll. A plain Crown of Ages is a fine helmet. This one has two sockets, fifteen percent physical damage reduction, and thirty all resistance, the top of every line it can roll. That stack is worth many times a low one. Same gold name, a completely different item, and the difference is invisible unless you read the numbers.",
    history: null,
    ifYouFind: "Two sockets and fifteen damage reduction is the jackpot. One socket and ten reduction is a cheaper helm wearing the same name."
  },
  {
    slug: "brimstone-barb",
    name: "Brimstone Barb",
    alias: "300 ED eth thrower",
    quality: "rare",
    type: "Stygian Pilum",
    sprite: "img/stygian-pilum.png",
    tooltip: [
      { t: "Throw Damage: 136 to 440", c: "white" },
      { t: "One-Hand Damage: 97 to 377", c: "white" },
      { t: "Quantity: 90", c: "white" },
      { t: "Required Dexterity: 102", c: "white" },
      { t: "Required Strength: 108", c: "white" },
      { t: "Required Level: 68", c: "white" },
      { t: "Javelin Class - Very Fast Attack Speed", c: "white" },
      "+40% Increased Attack Speed",
      "+300% Enhanced Damage",
      "+20 to Minimum Damage",
      "+206 to Attack Rating",
      "Adds 112-133 Fire Damage",
      "Replenishes Quantity",
      "Ethereal (Cannot be Repaired)"
    ],
    valueTier: "B",
    rarityTier: "Very Rare",
    obscurity: 4,
    why: "Throwing builds live and die on their weapon, and this rare beats the uniques. Three hundred enhanced damage is the most a rolled weapon can reach, and on a javelin that is more raw damage than the named throwers carry. It is ethereal, so the base climbs again, and that would normally kill a throwing weapon because you cannot repair it. This one replenishes its own stack, refilling to full on its own, so it never runs dry. A yellow javelin that outdamages everything gold in the slot, and nothing on the name warns you.",
    history: null,
    ifYouFind: "Throw it, never melee it. Ethereal cannot be repaired, and only the thrown stack refills. The maxed three hundred enhanced damage is the roll that makes it."
  },
  {
    slug: "pain-hood",
    name: "Pain Hood",
    alias: "2/20 druid circlet",
    quality: "rare",
    type: "Tiara",
    sprite: "img/tiara.png",
    tooltip: [
      { t: "Defense: 49", c: "white" },
      { t: "Durability: 25 of 25", c: "white" },
      { t: "Required Level: 67", c: "white" },
      "+2 to Druid Skill Levels",
      "+20% Faster Run/Walk",
      "+20% Faster Cast Rate",
      "+16 to Dexterity",
      "Cold Resist +17%",
      "Lightning Resist +55%",
      "Fire Resist +17%",
      "Poison Resist +17%"
    ],
    valueTier: "A",
    rarityTier: "Very Rare",
    obscurity: 4,
    why: "The best caster helm for a druid is often not a unique but a rare circlet like this. Two to all druid skills and twenty faster cast are the two lines every caster hunts, and here they arrive with run speed, dexterity and all four resistances on one Tiara. No unique druid helm matches the spread. A random yellow name hiding one of the best helms a storm or fire druid can wear.",
    history: null,
    ifYouFind: "Two class skills and twenty cast rate on a circlet is the jackpot. The resists and the speed on top are what push it past the uniques."
  },
  {
    slug: "wisp-projector",
    name: "Wisp Projector",
    alias: "20/20 Wisp",
    quality: "unique",
    type: "Ring",
    sprite: "img/wisp-projector.png",
    tooltip: [
      { t: "Required Level: 76", c: "white" },
      "10% Chance to Cast Level 16 Lightning on Striking",
      "Lightning Absorb 20%",
      "20% Better Chance of Getting Magic Items",
      "Level 7 Spirit of Barbs (11 Charges)",
      "Level 5 Heart of Wolverine (13 Charges)",
      "Level 2 Oak Sage (15 Charges)"
    ],
    valueTier: "A",
    rarityTier: "Rare",
    obscurity: 4,
    why: "Nobody looks twice at Wisp Projector. It reads like a novelty ring with a pile of charges. Then you notice the two lines that matter: lightning absorb up to twenty percent, and magic find up to twenty percent. Lightning is the deadliest damage in the game at the high end, so that absorb is worth real money, and the magic find rides along for free. The charges are a footnote. The two rolls are the item.",
    history: null,
    ifYouFind: "Read the absorb and the magic find. Twenty and twenty is the one people pay for."
  },
  {
    slug: "doom-stalker",
    name: "Doom Stalker",
    alias: "rare leech boots",
    quality: "rare",
    type: "Battle Boots",
    sprite: "img/battle-boots.png",
    tooltip: [
      { t: "Defense: 46", c: "white" },
      { t: "Durability: 11 of 18", c: "white" },
      { t: "Required Strength: 95", c: "white" },
      { t: "Required Level: 51", c: "white" },
      "+30% Faster Run/Walk",
      "+10% Faster Hit Recovery",
      "1% Life Stolen per Hit",
      "+20 to Life",
      "Replenish Life +10",
      "Lightning Resist +40%",
      "Fire Resist +40%"
    ],
    valueTier: "B",
    rarityTier: "Very Rare",
    obscurity: 4,
    why: "The slot most players fill with a unique and forget. This rare does more. Thirty faster run and walk, forty lightning and forty fire, twenty life with a little replenish, and the part people forget boots can even roll: life steal. Speed, two big resists, life and leech in one slot almost never land together. The leech here is one percent. A perfect roll pushes it higher.",
    history: null,
    ifYouFind: "Boots that leech are the tell most people miss. The run speed and the two resists are the base value. The life steal is the rare bonus, and this one is short of a maxed roll."
  },
  {
    slug: "herald-of-zakarum",
    name: "Herald of Zakarum",
    alias: "200 ED HoZ",
    quality: "unique",
    type: "Gilded Shield",
    sprite: "img/herald-of-zakarum.png",
    tooltip: [
      { t: "Defense: 507", c: "white" },
      { t: "Required Level: 42", c: "white" },
      { t: "Required Strength: 89", c: "white" },
      { t: "Chance to Block: 82%", c: "white" },
      "+200% Enhanced Defense",
      "30% Increased Chance of Blocking",
      "30% Faster Block Rate",
      "20% Bonus to Attack Rating",
      "+20 to Strength",
      "+20 to Vitality",
      "All Resistances +50",
      "+2 to Paladin Skill Levels",
      "+2 to Combat Skills (Paladin Only)"
    ],
    valueTier: "A",
    rarityTier: "Very Rare",
    obscurity: 3,
    why: "A Herald of Zakarum is a paladin staple, so people assume they are all the same. They are not. The enhanced defense rolls from a hundred and fifty to two hundred percent, and only a two hundred is worth chasing. Punch four sockets into that one and you have one of the best shields a paladin can hold. A low roll is a leveling shield. The gap between the two is enormous, and the tooltip barely hints at it.",
    history: null,
    ifYouFind: "Two hundred enhanced defense is the number. Anything lower is just a shield. Max roll, socket it and keep it."
  },
  {
    slug: "eth-sandstorm-trek",
    name: "Sandstorm Trek",
    alias: "eth Treks",
    quality: "unique",
    type: "Scarabshell Boots",
    sprite: "img/sandstorm-trek.png",
    tooltip: [
      { t: "Defense: 178", c: "white" },
      { t: "Required Level: 64", c: "white" },
      { t: "Required Strength: 91", c: "white" },
      "+170% Enhanced Defense",
      "+20% Faster Run/Walk",
      "+20% Faster Hit Recovery",
      "+15 to Strength",
      "+15 to Vitality",
      "Poison Resist +70%",
      "50% Slower Stamina Drain",
      "Repairs 1 Durability in 20 Seconds"
    ],
    valueTier: "B",
    rarityTier: "Rare",
    obscurity: 3,
    why: "Treks are cheap. Everyone has a pair, which is exactly why the good ones hide in plain sight. The chase is an ethereal pair with maxed strength and vitality. Ethereal usually means an item wears out and dies, but Sandstorm Trek repairs itself, so the ethereal version keeps its boosted defense forever and never breaks. The same boots most players vendor, except this one is worth a pile of runes.",
    history: null,
    ifYouFind: "Check for ethereal first, then the strength and vitality. Ethereal and 15/15 is the pair people hunt."
  },
  {
    slug: "eth-titans-revenge",
    name: "Titan's Revenge",
    alias: "eth Titan's",
    quality: "unique",
    type: "Ceremonial Javelin",
    sprite: "img/titans-revenge.png",
    tooltip: [
      { t: "Throw Damage: 79 to 212", c: "white" },
      { t: "Required Level: 42", c: "white" },
      { t: "Required Strength: 25", c: "white" },
      { t: "Required Dexterity: 109", c: "white" },
      "+200% Enhanced Damage",
      "Adds 25-50 Damage",
      "+2 to Amazon Skill Levels",
      "9% Life Stolen per Hit",
      "+30% Faster Run/Walk",
      "+20 to Strength",
      "+20 to Dexterity",
      "Replenishes Quantity (1 in 3 Seconds)",
      "+2 to Javelin and Spear Skills (Amazon Only)"
    ],
    valueTier: "A",
    rarityTier: "Rare",
    obscurity: 3,
    why: "A throwing javelin most people never think about twice. The trick is what happens when it is ethereal. Ethereal boosts the damage, and for a throwing weapon that depletes that would normally be a death sentence. Titan's Revenge replenishes its own stack, so an ethereal pair throws forever at boosted damage. Two amazon skills and thirty faster run ride along. It is the javazon's quiet grail, hiding as a common gold javelin.",
    history: null,
    ifYouFind: "Ethereal is the whole game here. An ethereal Titan's that replenishes is worth far more than the plain one you throw away."
  },
  {
    slug: "valkyrie-wing-08",
    grid: [2, 2],
    sockets: 1,
    name: "Valkyrie Wing",
    alias: "1.08 Valk Wing",
    quality: "unique",
    type: "Winged Helm",
    sprite: "img/winged-helm.png",
    lastPatch: "1.08",
    tooltip: [
      { t: "Defense: 127", c: "white" },
      { t: "Durability: 34 of 40", c: "white" },
      { t: "Required Strength: 118", c: "white" },
      { t: "Required Level: 44", c: "white" },
      "+30% Faster Run/Walk",
      "+30% Increased Attack Speed",
      "+30% Faster Cast Rate",
      "+30% Faster Hit Recovery",
      "+36 Defense",
      "Socketed (1)"
    ],
    valueTier: "B",
    rarityTier: "Very Rare",
    obscurity: 4,
    why: "The Valkyrie Wing that drops today gives run speed and amazon skills. This one, from patch 1.08, gave every speed bonus in the game at once. Thirty faster run, thirty attack speed, thirty faster cast, thirty faster hit recovery, all on one helm any class could wear. Nothing since has stacked four speed mods on a single item. It was too good, so it was rewritten.",
    history: "Patch 1.09 reworked Valkyrie Wing into the amazon helm it is now, trading the universal speed for class skills. The old 1.08 copies kept the four thirties. Like every legacy piece they live only on non-ladder, and they thin out every year. A speed stacker's relic from a version of the game that no longer exists.",
    ifYouFind: "Four separate thirty percent speed mods is the tell. That is the 1.08 helm, not the amazon one that drops now."
  },
  {
    slug: "grandfather-08",
    name: "The Grandfather",
    alias: "1.08 Grandfather",
    quality: "unique",
    type: "Colossus Blade",
    sprite: "img/colossus-blade.png",
    lastPatch: "1.08",
    tooltip: [
      { t: "Two-Hand Damage: 145 to 287", c: "white" },
      { t: "Required Level: 81", c: "white" },
      { t: "Required Strength: 189", c: "white" },
      { t: "Required Dexterity: 110", c: "white" },
      "+150% Enhanced Damage",
      "+150% Bonus to Attack Rating",
      "+175 to Life",
      "Increase Maximum Life 25%",
      "Increase Maximum Mana 25%",
      "+20 to Strength",
      "+20 to Dexterity",
      "Indestructible"
    ],
    valueTier: "B",
    rarityTier: "Mythic",
    obscurity: 4,
    why: "The Grandfather is a pure damage sword today. This one, from patch 1.08, was a fortress. It carried a hundred and seventy five flat life and raised your maximum life and mana by a quarter each, on top of the damage. No Grandfather made after 2001 has the maximum-life or maximum-mana lines at all. Same gold name, a completely different weapon underneath.",
    history: "Before the 1.09 rebalance the Grandfather stacked flat life, twenty five percent maximum life, and twenty five percent maximum mana. The patch stripped all three and replaced them with the per-level scaling the sword uses now. The old copies kept the survivability block, and because item stats never change after creation, that version cannot be made again. It is one of the most prized relics of the early game.",
    ifYouFind: "Look for the maximum-life and maximum-mana lines. The modern Grandfather has neither, so their presence dates the sword to before patch 1.09."
  },
  {
    slug: "vampire-gaze-08",
    name: "Vampire Gaze",
    alias: "1.08 Vamp Gaze",
    quality: "unique",
    type: "Grim Helm",
    sprite: "img/uniques/vampire-gaze-08.webp",
    tooltip: [
      { t: "Defense: 252", c: "white" },
      { t: "Required Level: 41", c: "white" },
      "Physical Damage Reduced by 25%",
      "Magic Damage Reduced by 15",
      "8% Life Stolen per Hit",
      "8% Mana Stolen per Hit",
      "15% Slower Stamina Drain"
    ],
    valueTier: "B",
    rarityTier: "Very Rare",
    lastPatch: "1.08",
    obscurity: 4,
    why: "The Vampire Gaze that drops today cuts physical damage by fifteen to twenty percent. This one, from patch 1.08, does a flat twenty five, with no cold damage cluttering the stat line. Five extra points of reduction does not sound like much until you stack it against everything else. Hardcore players chased these for years. It stopped dropping in this form long ago.",
    history: "Damage reduction was rebalanced after 1.08, and Vampire Gaze lost its fixed twenty five percent. The old copies kept it. Like every legacy item, they live only on non-ladder, and they get scarcer every year.",
    ifYouFind: "Check the damage reduced line. Twenty five percent flat means it is a 1.08 relic, not a modern drop."
  },
  {
    slug: "small-charm-5-20",
    name: "Shimmering Small Charm of Vita",
    alias: "5/20 small charm",
    quality: "magic",
    type: "",
    sprite: "img/small-charm.png",
    tooltip: [
      { t: "Required Level: 47", c: "white" },
      "+5 to All Resistances",
      "+20 to Life"
    ],
    valueTier: "A",
    rarityTier: "Very Rare",
    obscurity: 3,
    why: "A small charm takes one inventory square. This one gives five all resistance and twenty life for that square, both maxed. It is the best defensive small charm in the game, and players hoard whole rows of them. A perfect one costs more than plenty of uniques. Most people who find a near miss never notice how far off max it is.",
    history: null,
    ifYouFind: "Five and twenty is perfect. A four and eighteen looks almost identical and is worth a fraction. Read the numbers."
  },
  {
    slug: "small-charm-3-20-20",
    name: "Fine Small Charm of Vita",
    alias: "3/20/20 small charm",
    quality: "magic",
    type: "",
    sprite: "img/small-charm.png",
    tooltip: [
      { t: "Required Level: 39", c: "white" },
      "+3 to Maximum Damage",
      "+20 to Attack Rating",
      "+20 to Life"
    ],
    valueTier: "A",
    rarityTier: "Very Rare",
    obscurity: 2,
    why: "The melee version of the perfect small charm. Three maximum damage, twenty attack rating, twenty life, all maxed, in one square. Physical builds fill their inventory with these. The roll has to hit all three ceilings at once, which almost never happens, and that is what you pay for.",
    history: null,
    ifYouFind: "All three lines have to be maxed. Close does not count and is not worth much."
  },
  {
    slug: "grand-charm-skiller",
    name: "Harpoonist's Grand Charm of Vita",
    alias: "45-life skiller",
    quality: "magic",
    type: "",
    sprite: "img/grand-charm.png",
    tooltip: [
      { t: "Required Level: 48", c: "white" },
      "+1 to Javelin and Spear Skills (Amazon Only)",
      "+45 to Life"
    ],
    valueTier: "A",
    rarityTier: "Very Rare",
    obscurity: 3,
    why: "A grand charm that adds a whole skill level to one of your trees is already worth keeping. One that also rolls near-max life is an endgame item. Javazons, casters and warcry barbarians build their whole inventory out of these. The skill is the base value. The life roll on top is what turns a common skiller into an expensive one.",
    history: null,
    ifYouFind: "Any plus-skill grand charm is worth holding. One with forty plus life is worth real trade."
  },
  {
    slug: "jewel-40-15",
    name: "Jewel of Fervor",
    alias: "40/15 jewel",
    quality: "magic",
    type: "",
    sprite: "img/jewel.png",
    tooltip: [
      "+40% Enhanced Damage",
      "+15% Increased Attack Speed"
    ],
    valueTier: "S",
    rarityTier: "Very Rare",
    obscurity: 3,
    why: "One jewel. Forty percent enhanced damage and fifteen percent increased attack speed, both maxed. It is the single most valuable jewel in the game, and it trades in the high rune range, Ber to Jah. A whole endgame rune for one socketable. Almost every jewel is filler. This exact roll is a small fortune, and two lines are all that separate them.",
    history: null,
    ifYouFind: "Forty and fifteen, both maxed, or it is just another jewel. There is no close second on this one."
  },
  {
    slug: "rainbow-facet",
    name: "Rainbow Facet",
    alias: "5/5 Cold Facet",
    quality: "unique",
    type: "Jewel",
    sprite: "img/rainbow-facet.png",
    tooltip: [
      { t: "Required Level: 49", c: "white" },
      "100% Chance to Cast Level 43 Frost Nova when you Level-Up",
      "Adds 24-38 Cold Damage",
      "+5% to Cold Skill Damage",
      "-5% to Enemy Cold Resistance"
    ],
    valueTier: "A",
    rarityTier: "Rare",
    obscurity: 3,
    why: "A unique jewel that cuts enemy resistance and boosts your own elemental damage. There are eight versions, four elements times two triggers, and they are not equal. A perfect five-five of the right element on the level-up trigger is a caster chase. The poison ones and the death-trigger ones go for far less. Same gold name, eight very different price tags.",
    history: null,
    ifYouFind: "Match the element to your build, want the level-up trigger, and check for the five and five. Off-element or death-trigger is a different market."
  },
  {
    slug: "angelic-combo",
    name: "Angelic Halo + Wings",
    alias: "Angelics",
    quality: "set",
    type: "Ring + Amulet",
    sprite: "img/angelic-combo.png",
    tooltip: [
      { t: "Required Level: 12", c: "white" },
      "+12 to Attack Rating per Character Level",
      "+20 to Life",
      "Replenish Life +6"
    ],
    valueTier: "A",
    rarityTier: "Uncommon",
    obscurity: 2,
    why: "A seasoned player sees a set ring and amulet and moves on. That is the mistake. Worn together, the ring grants twelve attack rating for every character level. At level thirty that is hundreds of attack rating, more than a low-level character could ever get another way, and it makes a twink hit things it has no business hitting. The pieces are cheap. Knowing to pair them is the whole value.",
    history: null,
    ifYouFind: "Only worth it as the pair, ring and amulet together. One without the other is just a set piece."
  },
  {
    slug: "plague-bolt",
    grid: [2, 4],
    sockets: 1,
    name: "Plague Bolt",
    alias: "level-30 LLD bow",
    quality: "rare",
    type: "Gothic Bow",
    sprite: "img/rare-bow.png",
    tooltip: [
      { t: "Two-Hand Damage: 25 to 148", c: "white" },
      { t: "Required Dexterity: 118", c: "white" },
      { t: "Required Strength: 95", c: "white" },
      { t: "Required Level: 30", c: "white" },
      { t: "Bow Class - Very Fast Attack Speed", c: "white" },
      "+2 to Amazon Skill Levels",
      "+20% Increased Attack Speed",
      "+159% Enhanced Damage",
      "+18 to Maximum Damage",
      "+104 to Attack Rating",
      "Adds 10-14 Cold Damage",
      "6% Mana Stolen per Hit",
      "Socketed (1)"
    ],
    valueTier: "B",
    rarityTier: "Very Rare",
    obscurity: 4,
    why: "The required level thirty is the whole point. This is a level thirty dueling bow, and in that bracket a rare like this is a bowazon's endgame. Two amazon skills, twenty attack speed, a hundred and fifty nine enhanced damage and a socket, all under the level cap that defines the market. PvM players never see this economy. Inside it, a bow like this trades for real currency.",
    history: null,
    ifYouFind: "The level thirty requirement is the value, not a limit. It fits a popular dueling bracket, where two amazon skills and this much damage on one bow is a genuine chase."
  },
  {
    slug: "bloodfist",
    name: "Bloodfist",
    alias: "perfect Bloodfist",
    quality: "unique",
    type: "Heavy Gloves",
    sprite: "img/uniques/bloodfist.webp",
    tooltip: [
      { t: "Defense: 18", c: "white" },
      { t: "Required Level: 9", c: "white" },
      "+20% Enhanced Defense",
      "+10% Increased Attack Speed",
      "+30% Faster Hit Recovery",
      "+40 to Life",
      "+5 to Minimum Damage"
    ],
    valueTier: "A",
    rarityTier: "Rare",
    obscurity: 3,
    why: "Level nine gloves. A player rushing to endgame vendors them without a glance. In the low-level dueling bracket they are a staple, because forty life, ten attack speed and thirty faster hit recovery at that level requirement is enormous. A perfect pair with max enhanced defense trades for real currency inside that market.",
    history: null,
    ifYouFind: "The forty life and the speed are fixed. It is the market that makes them valuable, not the roll, so do not vendor a clean pair."
  },
  {
    slug: "cruel-matriarchal-bow",
    grid: [2, 4],
    sockets: 2,
    name: "Cruel Matriarchal Bow of Amplify Damage",
    alias: "hacked amp bow",
    quality: "magic",
    type: "",
    sprite: "img/matriarchal-bow.png",
    illicit: "Hacked",
    tooltip: [
      { t: "Two-Hand Damage: 95 to 223", c: "white" },
      { t: "(Amazon Only)", c: "red" },
      { t: "Required Dexterity: 187", c: "white" },
      { t: "Required Strength: 87", c: "white" },
      { t: "Required Level: 68", c: "white" },
      { t: "Bow Class - Very Fast Attack Speed", c: "white" },
      "5% Chance to Cast Level 1 Amplify Damage on Striking",
      "+1 to Bow and Crossbow Skills (Amazon Only)",
      "+30% Increased Attack Speed",
      "+376% Enhanced Damage",
      "Socketed (2)"
    ],
    valueTier: "A",
    rarityTier: "Mythic",
    obscurity: 5,
    why: "It calls itself a magic bow, but a magic item gets one prefix and one suffix, two lines at most. This has a curse on striking, a class skill, thirty attack speed and three hundred seventy six enhanced damage all at once. That is several affixes too many. It is a hacked bow wearing a legal-looking blue name, which is what made this kind so hard to catch in a trade window.",
    history: "The dangerous hacks were not the loud ones. A bow like this reads almost like a real magic drop, so it passed through trades a triple-absorb ring never would. It came from the same open-realm editing that produced the White Ring and Ith, tuned to look plausible. The tell is the affix count: no legitimate magic item can carry this many lines.",
    ifYouFind: "Count the blue lines. More than two on a magic item means it was edited, not dropped. This one has twice that."
  },
  {
    slug: "storm-circlet",
    name: "Storm Circlet",
    alias: "two-class hacked amulet",
    quality: "rare",
    type: "Amulet",
    sprite: "img/rare-amulet.png",
    illicit: "Hacked",
    tooltip: [
      { t: "Required Level: 34", c: "white" },
      "+2 to Necromancer Skill Levels",
      "+2 to Sorceress Skill Levels",
      "+20% Faster Cast Rate",
      "+18 to Strength",
      "+56 to Life",
      "+69 to Mana",
      "Cold Resist +23%",
      "Lightning Resist +23%",
      "Fire Resist +23%"
    ],
    valueTier: "A",
    rarityTier: "Mythic",
    obscurity: 5,
    why: "An amulet can grant skills to one class. This one grants two, plus two necromancer and plus two sorceress on the same neck, with cast rate and resists piled on. No random roll produces class bonuses for two classes at once. It reads as an ordinary godly rare until you notice it is helping two characters who could never both wear it.",
    history: "A subtle hack: a rare amulet edited to hold a second class's skills. Like the fake magic weapons of the era, it was built to survive a trade by looking almost right. It came from open-realm editing and the import bugs that leaked those items onto the ladder realms before the purges cleared them.",
    ifYouFind: "Two different class-skill lines on one amulet is the giveaway. The game only ever grants one."
  },
  {
    slug: "storm-needle",
    name: "Storm Needle",
    alias: "hacked 435 ED bow",
    quality: "rare",
    type: "Gothic Bow",
    sprite: "img/rare-bow.png",
    illicit: "Hacked",
    tooltip: [
      { t: "Two-Hand Damage: 58 to 267", c: "white" },
      { t: "Required Dexterity: 118", c: "white" },
      { t: "Required Strength: 95", c: "white" },
      { t: "Required Level: 48", c: "white" },
      { t: "Bow Class - Very Fast Attack Speed", c: "white" },
      "+20% Increased Attack Speed",
      "+435% Enhanced Damage",
      "+5 to Minimum Damage",
      "5% Bonus to Attack Rating",
      "+203 to Attack Rating",
      "Adds 48-75 Fire Damage",
      "+5 to Light Radius"
    ],
    valueTier: "B",
    rarityTier: "Mythic",
    obscurity: 5,
    why: "Four hundred thirty five percent enhanced damage on a bow that calls itself rare. The highest a single legitimate roll reaches is three hundred, and it cannot pair that with this many other lines. The numbers sit just past what the game allows, which is the signature of an item edited to look like a lucky drop instead of an obvious fake.",
    history: "Bows like this were built to slip past traders who knew the obvious hacks. Push the enhanced damage a little beyond the legal ceiling, add a few plausible lines, and it looks like the rare of a lifetime. It traces to the same open-realm editing era, and the same purges that cleared the White Ring took it too.",
    ifYouFind: "Know the ceilings. One enhanced-damage roll tops out near three hundred, and a rare holds six affixes at most. This clears both. Edited, not dropped."
  },
  {
    slug: "bugged-shaftstop",
    grid: [2, 3],
    sockets: 1,
    name: "Shaftstop",
    title: "Bugged Shaftstop",
    alias: "the ebug 2400 defense armor",
    quality: "unique",
    type: "Boneweave",
    sprite: "img/shaftstop.png",
    illicit: "Bugged",
    tooltip: [
      { t: "Defense: 2422", c: "white" },
      { t: "Durability: 33 of 46", c: "white" },
      { t: "Required Strength: 148", c: "white" },
      { t: "Required Level: 64", c: "white" },
      "+220% Enhanced Defense",
      "+250 Defense vs. Missile",
      "+60 to Life",
      "Damage Reduced by 30%",
      "Ethereal (Cannot be Repaired)",
      "Socketed (1)"
    ],
    valueTier: "A",
    rarityTier: "Very Rare",
    obscurity: 4,
    why: "Shaftstop is a beginner's armor. This one shows two thousand four hundred defense, roughly triple what the item can legitimately reach. It is the ethereal socketing bug: cube a socket into an ethereal armor and the game applies the ethereal defense bonus a second time, stacking a number the math never allows. Same gold name, an armor from a different reality.",
    history: "For a stretch of the game's life, adding a socket to an ethereal armor in the Horadric Cube doubled the ethereal defense bonus instead of applying it once. Players ran good bases through it on purpose, and ebugged armors became a quiet class of their own, worth far more than the clean version for the raw defense. Later patches fixed the recipe. The armors made before the fix kept their impossible numbers.",
    ifYouFind: "Compare the defense to the enhanced defense. If it is far higher than the math allows, it was ebugged before the fix, and it cannot be made now."
  },
  {
    slug: "bonesnap",
    name: "Bonesnap",
    alias: "classic melee chase",
    quality: "unique",
    type: "Maul",
    era: "Classic",
    sprite: "img/maul.png",
    tooltip: [
      { t: "Two-Hand Damage: 120 to 172", c: "white" },
      { t: "Required Strength: 69", c: "white" },
      { t: "Required Level: 24", c: "white" },
      "+300% Enhanced Damage",
      "+100% Damage to Undead",
      "+40% Chance of Crushing Blow",
      "Cold Resist +30%",
      "Fire Resist +30%"
    ],
    valueTier: "D",
    rarityTier: "Uncommon",
    obscurity: 4,
    why: "In classic Diablo 2 there were no runewords and no elite uniques, so the top of the melee ladder was a normal-tier unique like this. Bonesnap swings for up to three hundred percent enhanced damage with forty percent crushing blow, which tears a chunk off any target's current life no matter how much it has. At a level twenty four requirement, cubed up for more base damage, it was the weapon a classic barbarian actually wanted.",
    history: "Bonesnap was a classic melee staple, one of the hardest-hitting things a pre-expansion character could hold. Crushing blow made it a boss killer back when everyone's damage was small, and the low requirement let you swing it early. Lord of Destruction buried it under exceptional bases, elite uniques and runeword weapons, and a whole generation of players never learned it was once a chase item.",
    ifYouFind: "A classic answer to a problem the expansion later solved a dozen better ways. The crushing blow is why it mattered, not the raw number."
  },
  {
    slug: "twitchthroe",
    name: "Twitchthroe",
    alias: "Twitch",
    quality: "unique",
    type: "Studded Leather",
    sprite: "img/uniques/twitchthroe.webp",
    tooltip: [
      { t: "Defense: 60", c: "white" },
      { t: "Required Level: 16", c: "white" },
      { t: "Required Strength: 27", c: "white" },
      "20% Increased Attack Speed",
      "20% Faster Hit Recovery",
      "25% Increased Chance of Blocking",
      "+10 to Strength",
      "+10 to Dexterity"
    ],
    valueTier: "B",
    rarityTier: "Uncommon",
    obscurity: 2,
    why: "Attack speed, faster hit recovery, block and stats, all on a body armor with almost no requirement. A player leveling past it never looks back. In the low brackets it is a cornerstone, the armor that lets a twink hit breakpoints nothing else at that level can reach. Invisible to endgame, foundational to the people who live at level thirty.",
    history: null,
    ifYouFind: "Worthless to a rusher, a building block to a twink. Know which one you are before you sell it."
  },
  {
    slug: "silks-of-the-victor",
    name: "Silks of the Victor",
    alias: "classic caster armor",
    quality: "unique",
    type: "Ancient Armor",
    era: "Classic",
    sprite: "img/ancient-armor.png",
    tooltip: [
      { t: "Defense: 513", c: "white" },
      { t: "Required Strength: 100", c: "white" },
      { t: "Required Level: 28", c: "white" },
      "+120% Enhanced Defense",
      "+1 to All Skills",
      "5% Mana Stolen per Hit",
      "+2 to Light Radius"
    ],
    valueTier: "D",
    rarityTier: "Uncommon",
    obscurity: 4,
    why: "Plus one to all skills on a body armor sounds ordinary now. In classic Diablo 2 it was a grail. There was no Enigma, no Vipermagi, no Spirit Shroud, and almost nothing gave skills. A caster who wanted a skill level on the chest slot had this and little else, which is exactly why a plain unique Ancient Armor was the best caster body in the game for a stretch.",
    history: "Before the expansion, sources of plus skills barely existed. Silks of the Victor put a skill level on the chest when that was nearly impossible, and it sat in most serious classic casters' setups for that one reason. Lord of Destruction added skill armors and runewords that made it irrelevant almost overnight, and it faded into a curiosity.",
    ifYouFind: "The lesson is scarcity, not power. One skill level was worth a whole armor slot when the game had almost no other way to hand you one."
  },
  {
    slug: "spectral-shard",
    name: "Spectral Shard",
    alias: "Spec Shard",
    quality: "unique",
    type: "Blade",
    sprite: "img/uniques/spectral-shard.webp",
    tooltip: [
      { t: "One-Hand Damage: 4 to 15", c: "white" },
      { t: "Required Level: 25", c: "white" },
      { t: "Required Strength: 35", c: "white" },
      { t: "Required Dexterity: 51", c: "white" },
      "50% Faster Cast Rate",
      "+55 to Attack Rating",
      "All Resistances +10",
      "+50 to Mana"
    ],
    valueTier: "B",
    rarityTier: "Uncommon",
    obscurity: 3,
    why: "The damage on it is a joke, four to fifteen, so a melee player tosses it. Casters know better. Fifty percent faster cast rate at a level twenty five requirement is a huge breakpoint for the price, and it comes with mana and resistances attached. In the low-level caster bracket it is a default pick, and outside that bracket nobody notices it exists.",
    history: "For years the Spectral Shard was the caster weapon. Fifty faster cast at a level twenty five requirement was a breakpoint nothing cheaper could touch, so nearly every budget sorceress and every low-level caster dueler carried one. In that bracket it was so standard that seeing any other weapon was the surprise. Better cast weapons eventually arrived and pushed it down to a starter pick, but for a long stretch this flimsy little blade was the first thing a caster reached for.",
    ifYouFind: "Ignore the weapon damage. The fifty cast rate at a low level is the point."
  },
  {
    slug: "goldskin",
    name: "Goldskin",
    alias: "classic resist armor",
    quality: "unique",
    type: "Full Plate Mail",
    era: "Classic",
    sprite: "img/full-plate-mail.png",
    tooltip: [
      { t: "Defense: 402", c: "white" },
      { t: "Required Strength: 80", c: "white" },
      { t: "Required Level: 28", c: "white" },
      "+150% Enhanced Defense",
      "All Resistances +35",
      "100% Extra Gold from Monsters",
      "+2 to Light Radius",
      "Attacker Takes Damage of 10"
    ],
    valueTier: "D",
    rarityTier: "Uncommon",
    obscurity: 4,
    why: "Everyone remembers Goldskin as the joke armor that doubles your gold. Read the other line. In classic Diablo 2, before resistance gear was everywhere, a fixed thirty five to all resistances on the chest slot was a real answer to Hell's resistance penalties. The gold even mattered when it funded your gambling and repairs. A novelty today, a tank's staple then.",
    history: "Classic players had few ways to patch resistances, so a guaranteed plus thirty five all on a body armor carried real weight, and the extra gold was a genuine perk in an economy that ran on it. The expansion flooded the game with resist charms, runewords and better uniques, and Goldskin became the punchline it is now.",
    ifYouFind: "The resistances were the point, not the gold. A clean case of a stat's worth swinging entirely with the patch around it."
  },
  {
    slug: "deaths-combo",
    name: "Death's Guard + Death's Hand",
    alias: "cannot-be-frozen combo",
    quality: "set",
    type: "Sash + Leather Gloves",
    sprite: "img/deaths-combo.png",
    tooltip: [
      { t: "Required Level: 6", c: "white" },
      "Cannot Be Frozen",
      "30% Increased Attack Speed",
      "8% Life Stolen per Hit",
      "All Resistances +15",
      "Poison Resist +50%"
    ],
    valueTier: "B",
    rarityTier: "Uncommon",
    obscurity: 3,
    why: "Two cheap set pieces, a sash and a pair of gloves, both usable at level six. Worn together they give cannot be frozen, thirty percent attack speed, and eight percent life steal. Cannot be frozen with no real level requirement is the prize. It frees an amulet or ring slot a twink would otherwise spend on the same effect. The classic lesson in why junk-looking set pieces matter.",
    history: null,
    ifYouFind: "Only the pair matters. Together they hand a low-level character stats that normally cost a whole gear slot."
  },
  {
    slug: "wirts-leg",
    name: "Wirt's Leg",
    alias: "the cow-portal key",
    quality: "normal",
    type: "Club",
    sprite: "img/wirts-leg.png",
    tooltip: [
      { t: "One-Hand Damage: 2 to 8", c: "white" },
      { t: "Durability: 8 of 8", c: "white" },
      { t: "Required Level: 0", c: "white" }
    ],
    valueTier: "D",
    rarityTier: "Common",
    obscurity: 3,
    why: "A broken wooden leg that does almost no damage, and one of the most important items a farmer owns. Cube it with a Tome of Town Portal and it opens the Secret Cow Level. But a rule rides along that plenty of people still learn the hard way. If the Cow King dies in a game you created, that character can never open the cow portal again on that difficulty. No reset, no fix.",
    history: "The cow level was a premier experience and item farm, and the game gated it with a quiet, permanent punishment. Kill the King in your own game and the door shuts for good on that character and difficulty, which is why careful players herded the cows and left him standing. The lockout keys off the game's creator, not the killer, so you could still farm in a friend's game freely. Diablo 2 Resurrected removed it, which is itself a change to a twenty-year-old rule.",
    ifYouFind: "The trap is that it is per creator and per character, with no undo. Plenty of veterans have bricked a character's cow access without ever knowing the rule was there."
  },
  {
    slug: "tomb-reaver",
    name: "Tomb Reaver",
    alias: "3os Tomb Reaver",
    quality: "unique",
    type: "Cryptic Axe",
    sprite: "img/tomb-reaver.png",
    tooltip: [
      { t: "Two-Hand Damage: 125 to 570", c: "white" },
      { t: "Required Level: 84", c: "white" },
      { t: "Required Strength: 165", c: "white" },
      { t: "Required Dexterity: 103", c: "white" },
      "+280% Enhanced Damage",
      "+230% Damage to Undead",
      "+60% Increased Attack Speed",
      "All Resistances +50",
      "+80% Better Chance of Getting Magic Items",
      "+14 Life after each Kill",
      "Socketed (3)"
    ],
    valueTier: "S",
    rarityTier: "Very Rare",
    obscurity: 3,
    why: "Two Tomb Reavers can be worlds apart. It rolls one to three sockets and an enhanced damage range that swings by eighty percent. Only a three-socket copy at the top of the range is the one people chase. Then it hands you sixty attack speed, fifty all resist, and eighty magic find on top of monster damage. The name is the same on all of them. The roll is everything.",
    history: null,
    ifYouFind: "Count sockets, then read the enhanced damage. Three sockets and a high roll is the grail. One socket and a low roll is a different, cheaper axe."
  },
  {
    slug: "sacred-targe",
    grid: [2, 3],
    name: "Jeweler's Sacred Targe of Deflecting",
    alias: "paladin JMOD",
    quality: "magic",
    type: "",
    sprite: "img/sacred-targe.png",
    fill: ["img/rainbow-facet.png", "img/rainbow-facet.png", "img/rainbow-facet.png", "img/rainbow-facet.png"],
    fillLabel: "socket 4 lightning facets",
    fillTip: ["-20% to Enemy Lightning Resistance", "+20% to Lightning Skill Damage"],
    tooltip: [
      { t: "Defense: 141", c: "white" },
      { t: "Chance to Block: 76%", c: "white" },
      { t: "Durability: 27 of 46", c: "white" },
      { t: "(Paladin Only)", c: "red" },
      { t: "Required Strength: 86", c: "white" },
      { t: "Required Level: 47", c: "white" },
      "+30% Faster Block Rate",
      "20% Increased Chance of Blocking",
      "All Resistances +45",
      "Socketed (4)"
    ],
    valueTier: "A",
    rarityTier: "Very Rare",
    obscurity: 3,
    why: "The paladin's answer to the JMOD. A magic Sacred Targe with four sockets, the block rolls, and the paladin-only all-resistance bonus maxed at forty five. Fill the sockets with facets and you get a max-block shield with resistance already baked in that no runeword can match on this base. Paladins who know, hunt these. It reads as a blue shield and trades like an endgame piece.",
    history: null,
    ifYouFind: "Four sockets, the block rolls, and forty five resist on a magic Sacred Targe. That is the paladin grail. You socket it yourself."
  },
  {
    slug: "constricting-ring",
    illicit: "Bugged",
    name: "Constricting Ring",
    alias: "the ring that never dropped",
    quality: "unique",
    type: "Ring",
    sprite: "img/constricting-ring.png",
    tooltip: [
      { t: "Required Level: 95", c: "white" },
      "+15% to Maximum Fire Resist",
      "+15% to Maximum Cold Resist",
      "+15% to Maximum Lightning Resist",
      "+15% to Maximum Poison Resist"
    ],
    valueTier: "B",
    rarityTier: "Mythic",
    obscurity: 5,
    why: "A ring that raises every one of your resistance caps. Not your resistance, the cap itself, from seventy five to ninety across all four elements. Nothing else in the game does it, and nothing was ever supposed to. It sits in the files complete with stats and a level ninety five requirement, switched off so it can never drop.",
    history: "The Constricting Ring exists in uniqueitems.txt, the file that defines every unique, with its enable flag set to off. The developers built it, decided it was too strong to release, and left it disabled. The only copies that ever reached Battle.net came through an import bug from open and single-player realms. It is the purest case of an item that exists and does not exist at the same time.",
    ifYouFind: "You will not. It cannot drop. Any that exist slipped in through a bug two decades ago."
  },
  {
    slug: "oculus-soj",
    name: "Stone of Jordan",
    title: "Occy Ring",
    alias: "bugged Stone of Jordan",
    quality: "unique",
    illicit: "Bugged",
    type: "Ring",
    sprite: "img/uniques/stone-of-jordan.webp",
    tooltip: [
      { t: "Required Level: 42", c: "white" },
      "+3 to Sorceress Skill Levels",
      "+30% Faster Cast Rate",
      "25% Chance to Cast Level 1 Teleport when Struck",
      "All Resistances +20",
      "+20 to Vitality",
      "+20 to Energy",
      "50% Better Chance of Getting Magic Items"
    ],
    valueTier: "B",
    rarityTier: "Mythic",
    obscurity: 4,
    why: "Read the stats, then read the item type. Those are The Oculus's stats, a sorceress orb, sitting on a ring. Three sorceress skills, thirty faster cast, teleport when struck, all in a slot that should never hold them. A sorceress wearing one carried an extra orb's worth of power for free.",
    history: "The Occy Ring came out of the great bugged-item era, roughly 1.08 to 1.10, when a fusing glitch and open-realm imports put item properties onto the wrong bases. It was duped for years. Copies even split by region, the west and east versions carrying slightly different stats. Later purges wiped it out, and it no longer exists in the modern game.",
    ifYouFind: "It cannot exist legitimately. A Stone of Jordan with orb stats is a bugged relic, not a lucky drop."
  },
  {
    slug: "bugged-tals",
    grid: [2, 3],
    sockets: 1,
    name: "Tal Rasha's Guardianship",
    title: "Bugged Tal Rasha's Guardianship",
    alias: "Btal",
    quality: "set",
    illicit: "Bugged",
    type: "Lacquered Plate",
    sprite: "img/bugged-tals.png",
    tooltip: [
      { t: "Defense: 743", c: "white" },
      { t: "Required Level: 71", c: "white" },
      "+2 to All Skills",
      "+25% Faster Run/Walk",
      "Damage Reduced by 25%",
      "Magic Damage Reduced by 15",
      "All Resistances +40",
      "Requirements -60%",
      "Socketed (1)"
    ],
    valueTier: "A",
    rarityTier: "Very Rare",
    obscurity: 4,
    why: "The normal Tal Rasha's armor is a tidy magic-find piece. This one is best in slot. Somewhere in the bugged-item era it picked up two skills, twenty five percent faster run, twenty five percent damage reduction and a socket, none of which it is meant to have. For any build that does not run Enigma, a bugged Tal's is the armor to beat.",
    history: "Bugged items are real items that ended up better than the game ever intended, born in the same 1.08 to 1.10 window as the Occy Ring. The Btal is the most useful of them, which is why it still trades briskly on non-ladder. It cannot be made now. Every one in circulation is an old survivor, quietly duped along the way.",
    ifYouFind: "A Tal's armor with two skills and a socket is bugged. The normal one has neither. Non-ladder only."
  },
  {
    slug: "token-of-absolution",
    name: "Token of Absolution",
    alias: "the respec that took a decade",
    quality: "normal",
    type: "",
    sprite: "img/token-of-absolution.png",
    tooltip: [
      { t: "Cube four Essences to create", c: "grey" },
      "Resets all Skill and Stat points"
    ],
    valueTier: "C",
    rarityTier: "Uncommon",
    obscurity: 3,
    why: "For most of Diablo 2's life a misplaced skill point was permanent. There was no respec, and after the 1.10 synergy overhaul a single wrong point could quietly ruin a build. Then this arrived. Cube four Essences dropped by the act bosses and you get a full reset of skills and stats. One small item ended a decade of build anxiety.",
    history: "Original Diablo 2 committed you to every point you spent, which made theorycrafting a high-stakes gamble and delete-and-reroll the only real fix. Patch 1.13 added a free Akara respec once per difficulty and the Token of Absolution for unlimited ones. Behavior changed overnight: builds became experiments instead of commitments, and the reroll culture faded.",
    ifYouFind: "It is easy to forget the game ever worked the other way. For ten years this is the item players wished existed every time they misclicked a skill tree."
  },
  {
    slug: "jewelers-archon-plate",
    grid: [2, 3],
    name: "Jeweler's Archon Plate of the Whale",
    alias: "4os Archon Plate",
    quality: "magic",
    type: "",
    sprite: "img/archon-plate.png",
    sockets: 4,
    tooltip: [
      { t: "Defense: 512", c: "white" },
      { t: "Durability: 60 of 60", c: "white" },
      { t: "Required Strength: 103", c: "white" },
      { t: "Required Level: 63", c: "white" },
      "+100 to Life",
      "Socketed (4)"
    ],
    valueTier: "A",
    rarityTier: "Very Rare",
    obscurity: 4,
    why: "The Archon Plate is the lightest elite body armor, the lowest strength of the top tier. This one is magic, with four sockets and a hundred life on it. You cannot put Enigma in it, that needs a plain three-socket armor, but you can fill four sockets with resist runes or jewels and build a caster armor tuned to stats Enigma cannot give. Most players see a blue armor and move on. This one is a project piece worth real trade.",
    history: null,
    ifYouFind: "Four sockets and a big life roll on a low-strength magic Archon. That is a build-your-own armor, not vendor fodder."
  },
  {
    slug: "kano-zod",
    name: "Zod Rune",
    alias: "the rune Kano vendored",
    quality: "rune",
    type: "",
    sprite: "img/zod-rune.png",
    tooltip: [
      { t: "Required Level: 69", c: "white" },
      "Weapons: Indestructible",
      "Armor: Indestructible",
      "Helms: Indestructible",
      "Shields: Indestructible"
    ],
    valueTier: "S",
    rarityTier: "Mythic",
    obscurity: 3,
    why: "The Zod is the rarest rune in the game and the only thing that saves an ethereal item, because it makes anything indestructible. It is also the punchline to one of the best drop stories Diablo 2 has produced. In 2024 a speedrunner hit a Zod, a one in nearly three million drop, deep into a world-record run, and walked to the nearest vendor to sell it for pocket change on purpose.",
    history: "Kano was hours into a start-to-Ubers record attempt when the Zod fell, the kind of drop most players never see in twenty years. Stopping to use it would have cost time, so he vendored it for thirty five thousand gold, live, entirely for the bit. Gaming press covered it. The moment stuck because it took the single luckiest thing that can happen in Diablo 2 and threw it away for a laugh.",
    ifYouFind: "Its real use is unglamorous. Socket it into an ethereal weapon or armor and the item never breaks, the only way to keep an ethereal piece's boosted stats forever."
  },
  {
    slug: "artisans-diadem",
    grid: [2, 2],
    name: "Artisan's Diadem of Speed",
    alias: "3os caster Diadem",
    quality: "magic",
    type: "",
    sprite: "img/diadem.png",
    fill: ["img/rainbow-facet.png", "img/rainbow-facet.png", "img/rainbow-facet.png"],
    fillLabel: "socket 3 lightning facets",
    fillTip: ["-15% to Enemy Lightning Resistance", "+15% to Lightning Skill Damage"],
    tooltip: [
      { t: "Defense: 52", c: "white" },
      { t: "Durability: 11 of 20", c: "white" },
      { t: "Required Level: 64", c: "white" },
      "+30% Faster Run/Walk",
      "Socketed (3)"
    ],
    valueTier: "A",
    rarityTier: "Very Rare",
    obscurity: 4,
    why: "The Diadem is the best caster-helm base in the game. A magic one with three sockets and run speed is a blank canvas: drop in three facets and you have a helm that cuts enemy resistance and boosts your damage, tuned to your element. It reads as a junk blue circlet. It is one of the better caster helms you can build.",
    history: null,
    ifYouFind: "Three sockets on a Diadem is the prize. You fill it yourself, so an empty magic one with the sockets is what to grab."
  },
  {
    slug: "cruel-mythical-sword",
    name: "Cruel Mythical Sword",
    alias: "perfect eth Cruel sword",
    quality: "magic",
    type: "",
    sprite: "img/mythical-sword.png",
    tooltip: [
      { t: "One-Hand Damage: 240 to 300", c: "white" },
      { t: "Durability: 23 of 23", c: "white" },
      { t: "Required Dexterity: 114", c: "white" },
      { t: "Required Strength: 137", c: "white" },
      { t: "Required Level: 66", c: "white" },
      { t: "Sword Class - Fast Attack Speed", c: "white" },
      "+300% Enhanced Damage",
      "Ethereal (Cannot be Repaired)"
    ],
    valueTier: "B",
    rarityTier: "Very Rare",
    obscurity: 4,
    why: "A blue sword that reads like a vendor sale and hits like an elite runeword. Cruel is the most damage a magic weapon can roll, and a perfect one lands at three hundred percent. Ethereal stacks another fifty on the base. On a Mythical Sword, one of the hardest-hitting one-handers in the game, that is more raw damage than most gold weapons carry, for the price of a blue drop. Nothing on the name warns you.",
    history: null,
    ifYouFind: "Read the enhanced damage. A Cruel roll near three hundred on an ethereal elite base is a real weapon, not a vendor sale."
  },
  {
    slug: "cunning-greater-talons",
    name: "Cunning Greater Talons of Quickness",
    alias: "trapsin claw",
    quality: "magic",
    type: "",
    sprite: "img/greater-talons.png",
    tooltip: [
      { t: "One-Hand Damage: 21 to 36", c: "white" },
      { t: "Durability: 65 of 69", c: "white" },
      { t: "(Assassin Only)", c: "red" },
      { t: "Required Dexterity: 79", c: "white" },
      { t: "Required Strength: 79", c: "white" },
      { t: "Required Level: 46", c: "white" },
      { t: "Claw Class - Very Slow Attack Speed", c: "white" },
      "+3 to Traps (Assassin Only)",
      "+40% Increased Attack Speed",
      "+3 to Lightning Sentry (Assassin Only)"
    ],
    valueTier: "A",
    rarityTier: "Very Rare",
    obscurity: 4,
    why: "A trap assassin's dream claw. Plus three to the whole Traps tree and plus three to Lightning Sentry on top, on one magic claw, with forty attack speed. Dual wield two of these and you are stacking skills a runeword claw cannot touch. A blue weapon most players scroll right past, worth more than the orange ones to the right build.",
    history: null,
    ifYouFind: "The plus three traps and the plus three sentry together is the jackpot. One or the other is common. Both on one claw is not."
  },
  {
    slug: "lancers-matriarchal-javelin",
    name: "Lancer's Matriarchal Javelin of Quickness",
    alias: "+6 skill javazon javelin",
    quality: "magic",
    type: "",
    sprite: "img/matriarchal-javelin.png",
    tooltip: [
      { t: "Throw Damage: 35 to 66", c: "white" },
      { t: "One-Hand Damage: 30 to 54", c: "white" },
      { t: "Quantity: 76", c: "white" },
      { t: "(Amazon Only)", c: "red" },
      { t: "Required Dexterity: 151", c: "white" },
      { t: "Required Strength: 107", c: "white" },
      { t: "Required Level: 48", c: "white" },
      { t: "Javelin Class - Very Fast Attack Speed", c: "white" },
      "+6 to Javelin and Spear Skills (Amazon Only)",
      "+40% Increased Attack Speed"
    ],
    valueTier: "A",
    rarityTier: "Very Rare",
    obscurity: 4,
    why: "Six skill levels on a throwing weapon. Plus six to javelin and spear skills is more than any javazon gets from a single item anywhere else, and it comes with forty attack speed on a fast base. A blue javelin that outclasses the famous options for a javazon, and most people never think to read the skills line on a magic throwing weapon.",
    history: null,
    ifYouFind: "Plus six to javelin and spear on a magic javelin is the grail. Five is good. Six is a small fortune."
  },
  {
    slug: "volcanic-eldritch-orb",
    grid: [1, 3],
    name: "Volcanic Eldritch Orb",
    alias: "fire sorc caster orb",
    quality: "magic",
    type: "",
    sprite: "img/eldritch-orb.png",
    fill: ["img/rainbow-facet.png", "img/rainbow-facet.png"],
    fillLabel: "socket 2 fire facets",
    fillTip: ["-10% to Enemy Fire Resistance", "+10% to Fire Skill Damage"],
    tooltip: [
      { t: "One-Hand Damage: 18 to 42", c: "white" },
      { t: "Required Level: 60", c: "white" },
      { t: "(Sorceress Only)", c: "red" },
      { t: "Staff Class - Fast Attack Speed", c: "white" },
      "+3 to Fire Skills (Sorceress Only)",
      "+3 to Fire Mastery (Sorceress Only)",
      "+3 to Enchant (Sorceress Only)",
      "Socketed (2)"
    ],
    valueTier: "A",
    rarityTier: "Very Rare",
    obscurity: 4,
    why: "A fire sorceress dream stacked onto one blue orb. Three to the whole fire tree, three more to Fire Mastery, three more to Enchant, and two open sockets on top. Sorceress orbs roll hidden skill bonuses, and hitting three useful ones at once is what separates a fortune from a vendor sale. Drop two facets in and the fire damage climbs again.",
    history: null,
    ifYouFind: "Read the skill lines. One plus-three is common, three stacked plus-threes on the same orb is the jackpot."
  },
  {
    slug: "gaean-falcon-mask",
    grid: [2, 2],
    name: "Gaean Falcon Mask of the Sun",
    alias: "wind druid pelt",
    quality: "magic",
    type: "",
    sprite: "img/falcon-mask.png",
    fill: ["img/rainbow-facet.png", "img/rainbow-facet.png"],
    fillLabel: "socket 2 cold facets",
    fillTip: ["-10% to Enemy Cold Resistance", "+10% to Cold Skill Damage"],
    tooltip: [
      { t: "Defense: 12", c: "white" },
      { t: "Durability: 20 of 20", c: "white" },
      { t: "(Druid Only)", c: "red" },
      { t: "Required Strength: 28", c: "white" },
      { t: "Required Level: 45", c: "white" },
      "+3 to Elemental Skills (Druid Only)",
      "5% Bonus to Attack Rating",
      "+2 to Summon Grizzly (Druid Only)",
      "+3 to Tornado (Druid Only)",
      "+1 to Hunger (Druid Only)",
      "+6 to Light Radius",
      "Socketed (2)"
    ],
    valueTier: "A",
    rarityTier: "Very Rare",
    obscurity: 4,
    why: "A wind druid's whole shopping list on one blue pelt. Three to the elemental tree and three more straight to Tornado, plus grizzly and hunger, and two open sockets. Druid pelts roll hidden skill bonuses like weapons do, and landing the wind combo on one is rare. It out-skills the unique pelts for a storm druid and looks like nothing.",
    history: null,
    ifYouFind: "The plus-three elemental and plus-three Tornado together is the win. Fill the sockets and it is a top-tier storm helm."
  },
  {
    slug: "artisans-diadem-dr",
    grid: [2, 2],
    name: "Artisan's Diadem of Life Everlasting",
    alias: "26 DR caster Diadem",
    quality: "magic",
    type: "",
    sprite: "img/diadem.png",
    fill: ["img/rainbow-facet.png", "img/rainbow-facet.png", "img/rainbow-facet.png"],
    fillLabel: "socket 3 lightning facets",
    fillTip: ["-15% to Enemy Lightning Resistance", "+15% to Lightning Skill Damage"],
    tooltip: [
      { t: "Defense: 53", c: "white" },
      { t: "Durability: 20 of 20", c: "white" },
      { t: "Required Level: 64", c: "white" },
      "Damage Reduced by 26",
      "Socketed (3)"
    ],
    valueTier: "A",
    rarityTier: "Very Rare",
    obscurity: 4,
    why: "The other end of the Diadem chase. This one traded run speed for twenty six flat damage reduction, one of the strongest defensive stats in the game, on the best caster-helm base, with three sockets still open for facets. Flat damage reduction that high on a helm you can also stack facets into is a rare and greedy combination.",
    history: null,
    ifYouFind: "Twenty six damage reduced and three sockets on a Diadem is the defensive grail. The suffix is the value, the sockets are the bonus."
  }
];

if (typeof module !== "undefined" && module.exports) { module.exports = ITEMS; }
